import type { TypographyVariantsOptions } from "@mui/material/styles";

const systemDefaultFontFamilySansSerif = [
  "Inter",
  "Roboto",
  "sans-serif",
  '"Apple Color Emoji"',
  '"Segoe UI Emoji"',
  '"Segoe UI Symbol"',
  '"Noto Color Emoji"',
];

const typography: TypographyVariantsOptions = {
  htmlFontSize: 16,
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
  headerXL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 32,
    lineHeight: "40px",
    letterSpacing: "-0.03em",
  },
  headerL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 30,
    lineHeight: "36px",
    letterSpacing: "-0.02em",
  },
  headerM: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 24,
    lineHeight: "32px",
    letterSpacing: "-0.02em",
  },
  headerS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 16,
    lineHeight: "24px",
    letterSpacing: "-0.01em",
  },
  textXL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "26px",
  },
  textXLSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 18,
    lineHeight: "26px",
  },
  textXXL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 24,
    lineHeight: "32px",
  },
  textXXLSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 24,
    lineHeight: "32px",
  },
  textXXLB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 24,
    lineHeight: "32px",
  },
  textL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 16,
    lineHeight: "24px",
  },
  textM: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "20px",
  },
  textMSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
  },
  textS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 12,
    lineHeight: "16px",
  },
  textSSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "16px",
  },
  textXS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 400,
    fontSize: 10,
    lineHeight: "13px",
  },
  labelL: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 16,
    lineHeight: "24px",
    letterSpacing: "-0.01em",
  },
  labelLSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 16,
    lineHeight: "24px",
    letterSpacing: "-0.01em",
  },
  labelM: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
  },
  labelMSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 14,
    lineHeight: "20px",
  },
  labelMCaps: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 14,
    lineHeight: "20px",
    textTransform: "uppercase",
  },
  labelS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "16px",
  },
  labelSCapsSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 12,
    lineHeight: "16px",
    textTransform: "uppercase",
  },
  labelSSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 12,
    lineHeight: "16px",
  },
  labelSCaps: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "16px",
    textTransform: "uppercase",
    letterSpacing: "0.1px",
  },
  labelXS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 11,
    lineHeight: "16px",
  },
  labelXXS: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 500,
    fontSize: 10,
    lineHeight: "12px",
  },
  labelXXSCapsSB: {
    fontFamily: [...systemDefaultFontFamilySansSerif].join(","),
    fontWeight: 600,
    fontSize: 10,
    textTransform: "uppercase",
    lineHeight: "12px",
  },
};

export default typography;
